
package com.oracle.generatedStandAlone;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b05 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeWebService", targetNamespace = "http://lab1_standalone.oracle.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeWebService {


    /**
     * 
     * @return
     *     returns java.util.List<com.oracle.generatedStandAlone.Employee>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployees", targetNamespace = "http://lab1_standalone.oracle.com/", className = "com.oracle.generatedStandAlone.GetEmployees")
    @ResponseWrapper(localName = "getEmployeesResponse", targetNamespace = "http://lab1_standalone.oracle.com/", className = "com.oracle.generatedStandAlone.GetEmployeesResponse")
    @Action(input = "http://lab1_standalone.oracle.com/EmployeeWebService/getEmployeesRequest", output = "http://lab1_standalone.oracle.com/EmployeeWebService/getEmployeesResponse")
    public List<Employee> getEmployees();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.oracle.generatedStandAlone.Employee>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployeesByParameters", targetNamespace = "http://lab1_standalone.oracle.com/", className = "com.oracle.generatedStandAlone.GetEmployeesByParameters")
    @ResponseWrapper(localName = "getEmployeesByParametersResponse", targetNamespace = "http://lab1_standalone.oracle.com/", className = "com.oracle.generatedStandAlone.GetEmployeesByParametersResponse")
    @Action(input = "http://lab1_standalone.oracle.com/EmployeeWebService/getEmployeesByParametersRequest", output = "http://lab1_standalone.oracle.com/EmployeeWebService/getEmployeesByParametersResponse")
    public List<Employee> getEmployeesByParameters(
        @WebParam(name = "arg0", targetNamespace = "")
        Employee arg0);

}
